### ISSUE TITLE
Do you think it's possible to use this adapter to deploy with serverless

### ISSUE THREAD

**Issue by piolet** [jill64/sveltekit-adapter-aws#395]
Hi and thanx for your adapter.

I haven't tried it yet (mainly for lack of time), as I'm mainly doing research at the moment, but do you think it's possible to use the build of your adapter and make it work with Serverless (with Lift especially with this architecture: https://github.com/getlift/lift/blob/master/docs/server-side-website.md)

The lambda function described in this architecture could be the lambda dedicated to the server that is built via your adapter.

Do you see any counter-indications that would prevent this from working?

**Comment by jill64** [comment]
Thanks for opening this issue.

It may be possible to use the output artifacts from this adapter with the Serverless Framework (Lift) by adding processing under some constraints.

Adapter Configuration

|              |             |
| ------------ | ----------- |
| architecture | `lambda-s3` |
| deploy       | `false`     |
| cdn          | `false`     |

Serverless Framework Configuration

1. output directory (default: `build`)
2. configure to upload contents in `/build/s3` to S3
3. Upload contents in `/build/lambda` to Lambda.
4. Set `/build/lambda/server.js` as an entry point for Lambda
5. Configure CloudFront to redirect `/_app/*` to S3
6. Configure CloudFront to redirect everything except `/_app/*` to Lambda

With this in place, run `vite build` followed by `serverless deploy`.
In theory this should get it running, but there may be unknown issues.

**Comment by piolet** [comment]
thanks for your feedback.

I've just tried it, but just by setting it up, I'm thinking that with svelteKit, unfortunately, it can't work.
Indeed, the serverless.yml file will contain the environment variables to be deployed, but the build is done before independently of this serverless.yml.
As a result, it's difficult to deploy correctly while taking advantage of serverless. But this is more a problem with SvelteKit than with any framework or adapter.

What do you think?

**Comment by jill64** [comment]
Oops, I forgot about some viewpoints.

It might be a pretty hacky solution to create a monkey patch that reads the settings in `serverless.yml` and changes the adapter settings, and then add it to CI.

I can't determine from this context whether the problem belongs to sveltekit, but it looks difficult to use this adapter with `serverless`.

**Comment by piolet** [comment]
i forgot too ;)
we can close this "no" issue ;)
