### ISSUE TITLE
CDK bootstrap

### ISSUE THREAD

**Issue by dkorz-yolabs** [jill64/sveltekit-adapter-aws#399]
Is there a way to not run `npx cdk bootstrap` during the deploy? This requires additional permissions that I don't want to have the github action workflow and all developers to have. Devops runs the cdk bootstrap once on aws account + region creation and generally no one else can.

**Comment by jill64** [comment]
Thanks for opening this issue.

Currently, there is no way to skip the `npx cdk bootstrap` when deploying.

However, the bootstrap phase is not needed except the first time, so this suggestion makes sense.

I am too busy to respond right now, but I will try to resolve this issue soon.
