### ISSUE TITLE
Deployments fail intermittently

### ISSUE THREAD

**Issue by hiddengearz** [jill64/sveltekit-adapter-aws#485]
### Issue

While working on #481 I would have to constantly do deploy the app to test changes. It didn't take long before I started noticing deployments were failing.

After tons of troubleshooting I ultimately ended up completely removing my cloud formation stack and try deploying the cloudformation template generated by the adapter. This also only woks intermittently.

### Troubleshooting

I've tried

- destroying and deploying the stack
- Removing any and all resources created manually
- re-bootstraping

and I still can't figure out why it works sometimes and other times not...

### Justification 

Ultimately I believe the issue is that certain constructs are deploying/executing before all of the necessary files have been uploaded to S3. I've never run into this issue before but it's the only things that makes sense to me at this point.

I get the following error but it happens for all of the lambda functions, it changes per run. 

```
AWS::Lambda::LayerVersion                       | S3DeployAwsCliLayer4CECF5F7
Resource handler returned message: "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
```

If I understand the architecture correctly, `CustomCDKBucketDeploymentXXX` uploads the code needed for `ServerXXX` and  `S3DeployAwsCliLayerXXX` lambda function. If those files are not in the S3 bucket before they execute the entire CDK fails?

For example here is a snippet of my cloudformation template:

```
"S3DeployAwsCliLayer4CECF5F7": {
			"Type": "AWS::Lambda::LayerVersion",
			"Properties": {
				"Content": {
					"S3Bucket": "cdk-hnb659fds-assets-861314626580-us-east-1",
					"S3Key": "3322b7049fb0ed2b7cbb644a2ada8d1116ff80c32dca89e6ada846b5de26f961.zip"
				},
				"Description": "/opt/awscli/aws"
			},
			"Metadata": {
				"aws:cdk:path": "faulty-bedrock/S3Deploy/AwsCliLayer/Resource",
				"aws:asset:path": "asset.3322b7049fb0ed2b7cbb644a2ada8d1116ff80c32dca89e6ada846b5de26f961.zip",
				"aws:asset:is-bundled": false,
				"aws:asset:property": "Content"
			}
		},
```

If I check the S3 bucket `3322b7049fb0ed2b7cbb644a2ada8d1116ff80c32dca89e6ada846b5de26f961.zip` isn't there, so the error is correct.

---

### Evidence (I think)

Here is a copy of the logs from my last cloudformation deployment (this example also contains constructs from #411 so ignore them).

- On line 398 you can see `CustomCDKBucketDeployment` is in progress
- On line 333 you can see `S3DeployAwsCliLayer4CECF5F7` failed
- On line 289 you can see `CustomCDKBucketDeployment` fails

[cf_logs.json](https://github.com/jill64/sveltekit-adapter-aws/files/14413701/cf_logs.json)

**Comment by jill64** [comment]
Thanks for the detailed report.

Are you saying that the order in which the CDK resources are deployed is causing the problem?
We have confirmed that Lambda is deployed before the assets are uploaded to S3 in the demonstration environment, but no failures to deploy the entire CDK have occurred.

Hypothetically, the success or failure of the deployment may depend on the size of the CDK resource.
If I were to fix this with an adapter, how could I change the order in which the CDK resources are deployed?
(I am probably less familiar with CDK than you are)

**Comment by hiddengearz** [comment]
> I am probably less familiar with CDK than you are

I was hoping you would be more familiar with it than me but yes I think what you described is exactly what is going on.

This is largely due to seeing posts like [this](https://stackoverflow.com/questions/70328239/aws-s3-error-occurred-while-getobject-s3-error-code-nosuchkey-with-terraform), [this](https://stackoverflow.com/questions/61250772/how-can-i-create-a-dependson-relation-between-ec2-and-rds-using-aws-cdk) and ChatGPT's response:

```
Yes, it's possible that the error is occurring because the S3 bucket hasn't finished being deployed by the time the Lambda function starts to deploy. This can happen if there are dependencies between resources in your CDK stack, and one resource (in this case, the Lambda function) is being deployed before another resource (the S3 bucket) has completed deployment.

To address this issue, you can use AWS CloudFormation stack dependencies or AWS CDK constructs such as dependsOn to specify the order in which resources should be deployed. This ensures that dependencies are satisfied before resources are created or updated.

Here's how you can use dependsOn in your CDK code to ensure that the Lambda function waits for the S3 bucket to be deployed before proceeding:
...
```
> If I were to fix this with an adapter, how could I change the order in which the CDK resources are deployed?

I think by adding a [addDependency](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib-readme.html#construct-dependencies) onto the other lambda functions so they depend on `CustomCDKBucketDeployment` and see if that works. I'm going to play around with this over the next few days and see if it fixes the issue

**Comment by jill64** [comment]
Thanks for the additional info.
I followed the documentation and tried to set up Server Lambda deployments to depend on S3Deployment, but I get the following error.

```
Circular dependency between resources: [CloudFrontXXX, S3DeployCustomResourceXXX, ServerXXX, ServerinvokefunctionurlXXX, ServerFunctionUrlXXX, ServerServiceRoleXXX]
```

This adapter architecture uses Cloudfront to distribute client requests to Lambda and S3. [docs/lambda-s3/arch.png](https://github.com/jill64/sveltekit-adapter-aws/tree/main/docs/lambda-s3)
That is, Cloudfront depends on the FunctionURL of the Lambda ([cdk/arch/lambda-s3.ts Line 80](https://github.com/jill64/sveltekit-adapter-aws/blob/d47bc1ee4f03e20f9b3898fc0540b30485603755/cdk/arch/lambda-s3.ts#L80)) and S3Deployment depends on Cloudfront ([cdk/arch/lambda-s3.ts Line 102](https://github.com/jill64/sveltekit-adapter-aws/blob/d47bc1ee4f03e20f9b3898fc0540b30485603755/cdk/arch/lambda-s3.ts#L102)), an implicit dependency has already occurred.
Maybe this is why I get this error.

Do you think this is solvable?

**Comment by hiddengearz** [comment]
I believe this issue was my fault, I think there must of been an artifact from the stack I didn't delete that was causing the issue as I haven't experienced it since posting this.
