### ISSUE TITLE
Setting multiple cookie in same request not working

### ISSUE THREAD

**Issue by anilmagzter** [jill64/sveltekit-adapter-aws#604]
If we set more than one cookie in the same request, only the last one is used. 

For example
cookies.set('first', 'true', { path: '/' }); 
cookies.set('second', 'selected', { path: '/' }); 

Only the 'second' cookie is in the response and 'first' is ignored. Is it related to https://github.com/sveltejs/kit/issues/3460#issuecomment-1018760588

**Comment by jill64** [comment]
Thank you for opening this issue!

I have confirmed that the problem occurs.
Note the location of the obstruction for your records.

## 1. Buffered Response

It appears that the `Set-Cookie` header needs to be set using the `cookie` field.

https://github.com/jill64/sveltekit-adapter-aws/blob/3f7976eaa2889860106cf036d7d6b6a8c1042189/embed/arch/lambda-s3-buffered.ts#L49-L53

It is planned to be implemented in v1.6.0.

## 2. Streaming Response

I did some research, but couldn't find a workaround.

https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

It seems like there needs to be a way to set cookies other than using standard headers.

https://github.com/jill64/sveltekit-adapter-aws/blob/3f7976eaa2889860106cf036d7d6b6a8c1042189/embed/external/utils/qualified.ts#L6-L21

Does anyone know a solution regarding this?

**Comment by jill64** [comment]
`edge-bundled` is not working as well

**Comment by jill64** [comment]
After researching, it seems that with Lambda@edge and streaming responses, only a single key can be specified in HTTP headers, and multiple cookies cannot be returned.

This is an issue with the AWS Lambda platform and seems difficult to work around.

**Comment by jill64** [comment]
It was possible to return multiple headers with Lambda@Edge.
Available in v1.7.2.
I will continue to investigate the use of streaming responses.

**Comment by jill64** [comment]
It was possible to return multiple cookies with streaming response.
Available in v1.8.0
