### ISSUE TITLE
Routes triggering a download response of an empty file for 'lambda-s3' architecture

### ISSUE THREAD

**Issue by mblinusreimertz** [jill64/sveltekit-adapter-aws#632]
When I try to access my routes it also triggers a download of an empty file. I'm using the 'lambda-s3' architecture and I've followed the steps in the readme. Am I missing something?

**Comment by jill64** [comment]
This issue may be related to #540
What version of the library is there?

**Comment by mblinusreimertz** [comment]
Sorry, updating the adapter solved it. Thanks for the quick response! :)
